@echo off
echo Starting AciTech Cash Flow Application...
echo Python version:
python --version
echo.
echo Installing dependencies...
pip install -r requirements.txt
echo.
echo Initializing database...
python init_db.py
echo.
echo Starting application...
python wsgi.py